%% Test računanja prečnika pomoću normale
clear;
close all;
clc;

%% 1. Putanje projekta

folderSkripte = fileparts(mfilename('fullpath'));
folderProjekta = fileparts(folderSkripte);

folderVideo = fullfile(folderProjekta, 'Video');
folderRezultati = fullfile(folderProjekta, 'Rezultati');

putanjaRezultata = fullfile( ...
    folderRezultati, ...
    'rezultati_vertikalni_precnik.mat');

if ~isfile(putanjaRezultata)
    error([ ...
        'Rezultati vertikalnog prečnika nisu pronađeni. ' ...
        'Prvo pokrenite obradu celog videa.']);
end

%% 2. Učitavanje rezultata

ucitaniPodaci = load( ...
    putanjaRezultata, ...
    'rezultatiObrade');

rezultatiObrade = ...
    ucitaniPodaci.rezultatiObrade;

%% 3. Pronalaženje video-snimka

punaPutanja = ...
    rezultatiObrade.putanjaVidea;

if ~isfile(punaPutanja)

    [nazivFajla, putanjaFajla] = uigetfile( ...
        {'*.mp4;*.avi;*.mov', ...
         'Video fajlovi (*.mp4, *.avi, *.mov)'}, ...
        'Ponovo izaberite video-snimak', ...
        folderVideo);

    if isequal(nazivFajla, 0)
        error('Nije izabran video-snimak.');
    end

    punaPutanja = fullfile( ...
        putanjaFajla, ...
        nazivFajla);
end

videoObj = VideoReader(punaPutanja);

%% 4. Vremena za testiranje

vremenaZaTest = [2, 30, 60, 90, 120, 150];

maksimalnoVreme = ...
    rezultatiObrade.vremeRelativno(end);

vremenaZaTest = vremenaZaTest( ...
    vremenaZaTest <= maksimalnoVreme);

brojTestova = numel(vremenaZaTest);

%% 5. Priprema prikaza

figure( ...
    'Name', 'Prečnik pomoću normale', ...
    'NumberTitle', 'off');

brojKolonaGrafika = 2;
brojRedovaGrafika = ceil( ...
    brojTestova / brojKolonaGrafika);

tiledlayout( ...
    brojRedovaGrafika, ...
    brojKolonaGrafika, ...
    'TileSpacing', 'compact', ...
    'Padding', 'compact');

%% 6. Obrada izabranih frejmova

for indeksTesta = 1:brojTestova

    trazenoVreme = ...
        vremenaZaTest(indeksTesta);

    [~, indeksRezultata] = min(abs( ...
        rezultatiObrade.vremeRelativno - ...
        trazenoVreme));

    brojFrejma = ...
        rezultatiObrade.indeksiFrejmova( ...
            indeksRezultata);

    stvarnoVreme = ...
        rezultatiObrade.vremeRelativno( ...
            indeksRezultata);

    %% Učitavanje frejma

    vremeOdPocetkaVidea = ...
        (brojFrejma - 1) / ...
        rezultatiObrade.frameRate;

    videoObj.CurrentTime = min( ...
        vremeOdPocetkaVidea, ...
        max(0, videoObj.Duration - ...
        1 / rezultatiObrade.frameRate));

    frejm = readFrame(videoObj);
    frejmGray = im2gray(frejm);

    roiSlika = imcrop( ...
        frejmGray, ...
        rezultatiObrade.roiPozicija);

    %% Prethodno detektovane ivice

    gornjaIvica = double( ...
        rezultatiObrade.gornjaIvica( ...
            indeksRezultata, :));

    donjaIvica = double( ...
        rezultatiObrade.donjaIvica( ...
            indeksRezultata, :));

    vertikalniPrecnik = double( ...
        rezultatiObrade.precnikVertikalniPoTackama( ...
            indeksRezultata, :));

    %% Računanje normalnog prečnika

    [precnikNormala, presekX, presekY, detalji] = ...
        izracunaj_precnik_normalom( ...
            gornjaIvica, ...
            donjaIvica);

    medijanaVertikalnog = ...
        median(vertikalniPrecnik, 'omitnan');

    medijanaNormalnog = ...
        median(precnikNormala, 'omitnan');

    %% Prikaz slike i kontura

    grafik = nexttile;

    imshow(roiSlika, [], 'Parent', grafik);
    hold(grafik, 'on');

    brojKolonaROI = size(roiSlika, 2);
    xKoordinate = 1:brojKolonaROI;

    plot( ...
        grafik, ...
        xKoordinate, ...
        detalji.gornjaZagladjena, ...
        'r', ...
        'LineWidth', 1.4);

    plot( ...
        grafik, ...
        xKoordinate, ...
        detalji.donjaZagladjena, ...
        'c', ...
        'LineWidth', 1.4);

    %% Prikaz odabranih normala

    validniIndeksi = find( ...
        isfinite(precnikNormala));

    razmakIzmedjuNormala = 25;

    indeksiZaPrikaz = ...
        validniIndeksi( ...
            1:razmakIzmedjuNormala:end);

    for indeksKolone = indeksiZaPrikaz

        plot( ...
            grafik, ...
            [indeksKolone, presekX(indeksKolone)], ...
            [detalji.gornjaZagladjena(indeksKolone), ...
             presekY(indeksKolone)], ...
            'y', ...
            'LineWidth', 1);
    end

    hold(grafik, 'off');

    title( ...
        grafik, ...
        sprintf([ ...
            't = %.2f s | frejm %d\n' ...
            'vertikalni = %.2f px | normala = %.2f px'], ...
            stvarnoVreme, ...
            brojFrejma, ...
            medijanaVertikalnog, ...
            medijanaNormalnog));
end

sgtitle('Poređenje vertikalnog prečnika i prečnika duž normale');